name: image_build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  APPLICATION_NAME: matchreports

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: "0"

      - name: "Git: Configure local settings"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: "Setup: Calculate next version number"
        uses: mathieudutour/github-tag-action@v4.1
        id: version
        with:
          tag_prefix: "v"
          dry_run: true
          default_bump: patch
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Changelog: Create full changelog for commit"
        uses: nuuday/github-changelog-action@master
        with:
          filename: CHANGELOG.md
          next_version: ${{ steps.version.outputs.new_version }}

      - name: "Git: Commit changed files and tag release"
        run: |
          git add CHANGELOG.md
          git commit -m "Changelog updated" CHANGELOG.md
          git tag -m "$Tagged new version: ${{ steps.version.outputs.new_version }}" -fa ${{ steps.version.outputs.new_tag }}
          git push --tags

      - name: "Changelog: Create changelog for release"
        uses: nuuday/github-changelog-action@master
        id: changelog
        with:
          filename: CHANGELOG.md
          next_version: ${{ steps.version.outputs.new_version }}

      - name: "Github: Create release"
        uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          release_name: Release ${{ steps.version.outputs.new_version }}
          draft: false
          prerelease: false
          body: ${{ steps.changelog.outputs.changelog }}
  build_and_push:
    runs-on: ubuntu-latest
    needs: [tag_and_release]
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - id: repo_string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Build and push
        id: docker_build
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ steps.repo_string.outputs.lowercase }}/${APPLICATION_NAME}:${{needs.tag_and_release.outputs.release_tag}}
          IMAGE_ID_LATEST=docker.pkg.github.com/${{ steps.repo_string.outputs.lowercase }}/${APPLICATION_NAME}:latest
          docker build -t ${IMAGE_ID} --build-arg PROD_ENV=production -f Dockerfile . 
          docker push ${IMAGE_ID}
          docker tag ${IMAGE_ID} ${IMAGE_ID_LATEST}
          docker push ${IMAGE_ID_LATEST}
  buildx:
    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm/v7,linux/arm64
    needs: [tag_and_release]
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - id: repo_string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Set tag var
        id: vars
        run: echo ::set-output name=docker_name::${{ steps.repo_string.outputs.lowercase }}/${APPLICATION_NAME}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: DOCKER_TARGET_PLATFORM
          build-args: "PROD_ENV=production"
          push: true
          tags: ${{ steps.vars.outputs.docker_name }}:${{needs.tag_and_release.outputs.release_tag}}-armv7,${{ steps.vars.outputs.docker_name }}:${{needs.tag_and_release.outputs.release_tag}}-arm64
      - name: Retag to latest - arm64
        uses: ybrin/retag-docker-image@0.1.0
        with:
          registry: docker login docker.pkg.github.com
          name: ${{ steps.vars.outputs.docker_name }}
          old_tag: ${{needs.tag_and_release.outputs.release_tag}}-arm64
          new_tag: latest-arm64
      - name: Retag to latest - armv7
        uses: ybrin/retag-docker-image@0.1.0
        with:
          registry: docker login docker.pkg.github.com
          name: ${{ steps.vars.outputs.docker_name }}
          old_tag: ${{needs.tag_and_release.outputs.release_tag}}-armv7
          new_tag: latest-armv7
